server:
  port: 8090
  
spring:  jackson:    time-zone: America/Bogota
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.64.1:54321/
    username: postgres
    password: postgres
      