server:
  port: 8091
zuul:
  routes:
    users:
      path: /**
      url: http://localhost:8092/

gateway-security:
  allowed-paths: ["/ip-information/**", "/actuator/health", "/actuator/**" ]

management:
  endpoints:
    web:
      exposure:
        include: health
