server:
  port: 8092
  
geolocation:
  url: "https://api.ip2country.info/ip?"
  
country:
  url: "https://restcountries.eu/rest/v2/alpha/"
  
coin:
  url: "http://data.fixer.io/api/latest"
  param-key: "access_key"
  param-value: "9dd409bf55953525b107328e631f70e6"
  symbols: "usd,eur"

blacklist:
  url: "http://localhost:8090/retrieve"  



    
logging:
  level:
    reactor:
      netty:
        http:
          client: INFO
